coco_names = [
    '__unlabeled__',
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bus',
    'train',
    'truck',
    'boat',
    'traffic light',
    'fire hydrant',
    'street sign',  # removed
    'stop sign',
    'parking meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'hat',  # removed
    'backpack',
    'umbrella',
    'shoe',  # removed
    'eye glasses',  # removed
    'handbag',
    'tie',
    'suitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports ball',
    'kite',
    'baseball bat',
    'baseball glove',
    'skateboard',
    'surfboard',
    'tennis racket',
    'bottle',
    'plate',  # removed
    'wine glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot dog',
    'pizza',
    'donut',
    'cake',
    'chair',
    'couch',
    'potted plant',
    'bed',
    'mirror',  # removed
    'dining table',
    'window',  # removed
    'desk',  # removed
    'toilet',
    'door',  # removed
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'blender',  # removed
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrush',
    'hair brush',  # removed
    'banner',   # ### begin COCO stuff ###
    'blanket',
    'branch',
    'bridge',
    'building-other',
    'bush',
    'cabinet',
    'cage',
    'cardboard',
    'carpet',
    'ceiling-other',
    'ceiling-tile',
    'cloth',
    'clothes',
    'clouds',
    'counter',
    'cupboard',
    'curtain',
    'desk-stuff',
    'dirt',
    'door-stuff',
    'fence',
    'floor-marble',
    'floor-other',
    'floor-stone',
    'floor-tile',
    'floor-wood',
    'flower',
    'fog',
    'food-other',
    'fruit',
    'furniture-other',
    'grass',
    'gravel',
    'ground-other',
    'hill',
    'house',
    'leaves',
    'light',
    'mat',
    'metal',
    'mirror-stuff',
    'moss',
    'mountain',
    'mud',
    'napkin',
    'net',
    'paper',
    'pavement',
    'pillow',
    'plant-other',
    'plastic',
    'platform',
    'playingfield',
    'railing',
    'railroad',
    'river',
    'road',
    'rock',
    'roof',
    'rug',
    'salad',
    'sand',
    'sea',
    'shelf',
    'sky-other',
    'skyscraper',
    'snow',
    'solid-other',
    'stairs',
    'stone',
    'straw',
    'structural-other',
    'table',
    'tent',
    'textile-other',
    'towel',
    'tree',
    'vegetable',
    'wall-brick',
    'wall-concrete',
    'wall-other',
    'wall-panel',
    'wall-stone',
    'wall-tile',
    'wall-wood',
    'water-other',
    'waterdrops',
    'window-blind',
    'window-other',
    'wood'
]

voc_names = [
    '__unlabeled__',
    'aeroplane',
    'bicycle',
    'bird',
    'boat',
    'bottle',
    'bus',
    'car',
    'cat',
    'chair',
    'cow',
    'diningtable',
    'dog',
    'horse',
    'motorbike',
    'person',
    'pottedplant',
    'sheep',
    'sofa',
    'train',
    'tvmonitor'
]

coco_id_to_name = {index: name for index, name in enumerate(coco_names)}
coco_name_to_id = {name: index for index, name in enumerate(coco_names)}

# including __unlabled__ and removed labels
coco_num_obj_classes = 92
coco_num_all_classes = len(coco_names)

voc_id_to_name = {index: name for index, name in enumerate(voc_names)}
voc_name_to_id = {name: index for index, name in enumerate(voc_names)}

# including __unlabled__
voc_num_obj_classes = len(voc_names)
